### ISSUE TITLE
Explore creating a "bundle" module

### ISSUE THREAD

**Issue by akrigline** [bryancasler/Bryans-Preferred-Modules-for-FoundryVTT#1]
With 0.6.6's new [module dependency system](https://foundryvtt.com/article/module-development/#options), it would be theoretically possible to release a "module bundle" module with a simple manifest that only needs to list its dependencies.

Potentially interesting way to make it easier for people to install the whole batch of your curated list at once.

**Comment by bryancasler** [comment]
I like this idea, but I'm lazy :D Going to try and get another import/export module to add support (https://github.com/cstadther/adventure-import-export/issues/106). Plus realistically it would be super helpful to both be able to bring over modules AND the assets I want to use, rather than making that a two step process.

**Comment by bryancasler** [comment]
@akrigline I now have a "Quickstart Guide with Video Walkthrough" that includes an import file to supercharge your set up.
